server:
  port: 2000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.169.2:8848
#测试网关
    gateway:
      routes:
        - id: test_route
          uri: https://blog.csdn.net/
          predicates:
            - Query=url

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
